/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <fstream>
using std::istream;
using std::ostream;
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int LEX::yylex()


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 47
#define YY_END_OF_BUFFER 48
static yyconst short int yy_accept[146] =
    {   0,
        5,    5,    0,    0,    0,    0,    0,    0,   48,   47,
       44,   46,   21,   32,   45,   16,   45,   12,   22,   23,
       15,   28,   15,    7,   16,    4,   29,   18,   19,   18,
        2,    2,   26,   27,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,   24,   47,   25,   36,   35,
       34,   36,   40,   38,   40,   42,   43,   42,   44,   18,
       20,   10,    9,   10,   17,    6,    5,   31,   30,    7,
        4,    3,    3,    3,    2,    2,    0,    0,    2,    2,
        2,    2,    2,    2,    1,    2,    2,    2,    1,    2,
        2,    2,    2,    2,    0,   33,   37,    0,   39,   41,

        0,   11,   10,   10,    6,    8,    8,    3,    3,    3,
        5,    7,    7,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,   14,   13,    7,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,    1,   21,   22,
       23,   24,    1,    7,   25,   25,   25,   25,   26,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       27,   28,   29,    7,   30,    7,   31,   32,   33,   34,

       35,   36,   25,   37,   38,   25,   39,   40,   25,   41,
       42,   25,   25,   43,   44,   45,   46,   47,   48,   25,
       25,   25,   49,   50,   51,    7,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[52] =
    {   0,
        1,    2,    3,    2,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    4,    1,    5,    6,
        1,    1,    1,    1,    6,    6,    1,    2,    1,    7,
        5,    5,    6,    6,    6,    5,    6,    6,    6,    6,
        5,    6,    5,    6,    5,    6,    5,    6,    1,    1,
        1
    } ;

static yyconst short int yy_base[158] =
    {   0,
        0,    0,   49,   50,   51,   54,   55,   56,  290,  420,
       58,  420,  257,  420,  420,  420,  255,   53,  420,  420,
      246,  420,  238,   47,   52,   54,  420,  228,  224,  211,
       56,   71,  420,  420,    0,   73,   75,   65,  183,   73,
       83,   86,   82,   90,   92,  420,  159,  420,  420,  420,
      420,   95,  420,  420,  132,  420,  420,  170,  107,  420,
      420,  174,  167,  127,  420,  121,  125,  420,  420,  130,
      145,  137,  162,    0,    0,  107,  166,  170,  177,  160,
      125,  166,  162,  163,  164,  170,  176,  172,  180,  183,
      184,  194,  195,  201,  150,  420,  420,  241,  420,  420,

      163,  129,   98,   73,  221,  229,  236,    0,  238,  245,
      246,  250,  254,  241,  240,  242,  243,  255,  257,  259,
      256,  263,  265,  271,  186,   62,   51,  294,  279,  281,
      280,  287,  288,  289,  298,  267,  299,  301,  308,  309,
      310,  312,  316,  319,  420,  361,  368,  375,  382,  386,
      389,  392,  398,  403,  407,  409,  412
    } ;

static yyconst short int yy_def[158] =
    {   0,
      145,    1,  146,  146,  147,  147,  148,  148,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  149,  145,  145,
      145,  145,  145,  145,  145,  150,  145,  145,  145,  145,
      151,  151,  145,  145,  152,  151,  151,   37,   32,   37,
       37,   41,   41,   41,   41,  145,  145,  145,  145,  145,
      145,  153,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  154,  154,  154,  145,  145,  155,  145,  145,  145,
      150,  156,  156,  157,  152,   41,  145,  145,   32,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,  145,  145,  145,  145,  145,  145,

      154,  154,  154,  154,  145,  155,  155,  157,  156,   73,
      155,  145,  145,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,  154,  154,  145,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,    0,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145
    } ;

static yyconst short int yy_nxt[472] =
    {   0,
       10,   11,   12,   11,   13,   14,   15,   16,   17,   18,
       19,   20,   16,   21,   22,   23,   24,   25,   26,   26,
       27,   28,   29,   30,   31,   32,   33,   10,   34,   35,
       31,   36,   37,   38,   39,   40,   31,   41,   31,   31,
       31,   31,   42,   43,   31,   31,   44,   45,   46,   47,
       48,   50,   50,   54,   51,   51,   54,   57,   57,   59,
      126,   59,   63,   66,   68,   67,   67,   58,   58,   69,
       70,  126,   71,   71,   75,   75,   52,   52,   55,   73,
       64,   55,  127,   74,   77,   75,   77,   78,   73,   79,
       79,   75,   75,   75,   75,   76,   95,   96,   95,   84,

       75,   76,   75,   76,   75,   81,   85,  127,   59,   76,
       59,   82,   87,   76,   88,   80,   83,   76,   89,   76,
       91,   76,   76,   90,   76,   76,   76,   76,   94,   92,
       76,   93,   76,   98,   99,   98,  103,   66,  126,  105,
      105,   66,   76,   67,   67,  104,   66,   76,   67,   67,
      107,   95,   96,   95,  104,  108,  108,  104,  104,  107,
       76,   70,  104,   71,   71,   76,  108,  104,  115,  104,
       73,  104,  126,  104,   74,   77,  102,   77,   78,   73,
      110,  110,   78,  102,  111,  111,   78,  100,  112,  112,
      145,  108,  145,  113,  114,   76,  116,   76,  118,   76,

       76,   76,  117,   76,   76,   76,   76,   76,   61,  119,
       76,   76,   76,  120,   89,   76,   76,  121,   76,   76,
       76,   76,   86,   76,   76,  136,   76,   89,  122,   76,
       76,  123,  124,   60,   76,   76,   76,   66,  125,  105,
      105,   76,   98,   99,   98,  145,   60,  145,  145,   77,
       60,   77,   78,   65,  111,  111,  108,  108,  145,   65,
      145,  113,  113,   61,  111,  111,   78,  108,  112,  112,
      113,  129,  128,  128,   89,   76,   76,   76,   76,   60,
       76,   76,   76,   76,   89,  131,  133,  130,  132,  145,
       76,   76,   76,   89,   76,   76,   76,   76,   76,   76,

       76,   89,   76,   76,   89,   76,   76,   76,  134,  135,
      113,   76,  128,  128,   76,   76,   76,   89,  137,   76,
       76,   76,   76,   76,   76,  138,  139,   76,   76,   76,
      141,  140,   89,   76,   76,  145,   76,  145,   76,  142,
      143,   76,   89,   76,   76,   76,   89,   76,   76,   89,
       76,   76,   76,   89,   76,  145,   76,  144,  145,   76,
       89,   49,   49,   49,   49,   49,   49,   49,   53,   53,
       53,   53,   53,   53,   53,   56,   56,   56,   56,   56,
       56,   56,   62,   62,  145,   62,   62,   62,   62,   72,
       72,   72,   72,   76,   76,   76,   75,   75,   75,   97,

       97,  145,   97,  101,  101,  145,  101,  101,  101,  101,
      106,  106,  106,  109,  109,  109,  108,  108,  108,    9,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145
    } ;

static yyconst short int yy_chk[472] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    3,    4,    6,    7,    8,   11,
      127,   11,   18,   24,   25,   24,   24,    7,    8,   25,
       26,  126,   26,   26,   31,   31,    3,    4,    5,   26,
       18,    6,  104,   26,   32,   31,   32,   32,   26,   32,
       32,   36,   36,   37,   37,   38,   52,   52,   52,   38,

       32,   38,   36,   40,   37,   37,   38,  103,   59,   40,
       59,   37,   40,   41,   40,   36,   37,   43,   41,   41,
       42,   42,   43,   41,   41,   44,   42,   45,   45,   43,
       44,   44,   45,   55,   55,   55,   64,   66,  102,   66,
       66,   67,   76,   67,   67,   64,   70,   76,   70,   70,
       67,   95,   95,   95,   64,   72,   72,   64,   64,   67,
       81,   71,   64,   71,   71,   81,   72,   64,   81,   64,
       71,   64,  101,   64,   71,   73,   63,   73,   73,   71,
       73,   73,   77,   62,   77,   77,   78,   58,   78,   78,
       79,   73,   79,   79,   80,   80,   82,   83,   84,   85,

       80,   82,   83,   84,   85,   86,   82,   88,   47,   85,
       86,   87,   88,   86,   88,   89,   87,   87,   90,   91,
       89,  125,   39,   90,   91,  125,  125,   90,   91,   92,
       93,   92,   93,   30,   92,   93,   94,  105,   94,  105,
      105,   94,   98,   98,   98,  106,   29,  106,  106,  107,
       28,  107,  107,   23,  107,  107,  109,  109,  110,   21,
      110,  110,  111,   17,  111,  111,  112,  109,  112,  112,
      113,  114,  113,  113,  115,  115,  114,  116,  117,   13,
      115,  114,  116,  117,  116,  118,  121,  117,  119,    9,
      118,  121,  119,  120,  120,  118,  121,  119,  122,  120,

      123,  136,  136,  122,  124,  123,  124,  136,  122,  123,
      128,  124,  128,  128,  129,  131,  130,  129,  130,  129,
      131,  130,  132,  133,  134,  131,  132,  132,  133,  134,
      135,  134,  133,  135,  137,    0,  138,    0,  135,  137,
      138,  138,  139,  139,  140,  141,  141,  142,  139,  140,
      141,  143,  142,  144,  144,    0,  143,  142,    0,  144,
      143,  146,  146,  146,  146,  146,  146,  146,  147,  147,
      147,  147,  147,  147,  147,  148,  148,  148,  148,  148,
      148,  148,  149,  149,    0,  149,  149,  149,  149,  150,
      150,  150,  150,  151,  151,  151,  152,  152,  152,  153,

      153,    0,  153,  154,  154,    0,  154,  154,  154,  154,
      155,  155,  155,  156,  156,  156,  157,  157,  157,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "lexer.l"
#define INITIAL 0
#define STRING 1

#define COMMENT_SINGLE_LINE 2

#define COMMENT_MULTI_LINE 3

#line 11 "lexer.l"
#include<iostream>
#include<cstdio>
#include<cstring>
#include <string>
#include "SymbolTable.h"

using namespace std;

int lineCount=1,tmpLineCount,errorCount=0;
FILE *logFile,*tokenFile;
string stringBody;
string logStringBody;
string commentBody;
SymbolTable *symbolTable;

string charPointerToString( char* buf) {
    int max=strlen(buf);
    size_t len = 0;
    while( (len < max) && (buf[ len ] != '\0') ) {
        len++;
    }
    return string( buf, len );
}

#line 521 "lex.yy.cc"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif


#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 41 "lexer.l"

#line 650 "lex.yy.cc"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = &cin;

		if ( ! yyout )
			yyout = &cout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 146 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 420 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 42 "lexer.l"
{
    //keywords
    char *upperCaseKeyword=(char*)malloc(sizeof(char*)*strlen(yytext));
    int i;
    for(i=0;i<strlen(yytext);i++)
        upperCaseKeyword[i]=yytext[i]-32;
    fprintf(logFile, "Line no %d: Token<%s> Lexeme %s found\n\n",lineCount,upperCaseKeyword,yytext);
    fprintf(tokenFile,"<%s> ",upperCaseKeyword);
    free(upperCaseKeyword);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 53 "lexer.l"
{
    fprintf(logFile,"Line no %d: Token <ID> Lexeme %s found\n\n",lineCount,yytext);
    fprintf(tokenFile,"<ID, %s> ",yytext);
    //cout<<endl<<charPointerToString(yytext);
    //cout<<symbolTable->printAllScopes();
    symbolTable->insertSymbol(charPointerToString(yytext),"ID");
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 61 "lexer.l"
{
    //Invalid prefix before an id
    errorCount++;
    fprintf(logFile,"Error at line no %d: Invalid prefix before ID : %s \n\n",lineCount,yytext);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 67 "lexer.l"
{
    //integer constant
    fprintf(logFile,"Line no %d: Token <CONST_INT> Lexeme %s found\n\n",lineCount,yytext);
    fprintf(tokenFile,"<CONST_INT, %s> ",yytext);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 73 "lexer.l"
{
    //floating constant
    fprintf(logFile,"Line no %d: Token <CONST_FLOAT> Lexeme %s found\n\n",lineCount,yytext);
    fprintf(tokenFile,"<CONST_FLOAT, %s> ",yytext);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 79 "lexer.l"
{
    //Too many decimal point error
    errorCount++;
    fprintf(logFile,"Error at line no %d: Too many decimal points : %s \n\n",lineCount,yytext);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 85 "lexer.l"
{
    //Illed formed number
    errorCount++;
    fprintf(logFile,"Error at line no %d: Ill formed number : %s \n\n",lineCount,yytext);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 91 "lexer.l"
{
    //Invalid suffix after a numeric value
    errorCount++;
    fprintf(logFile,"Error at line no %d: Invalid suffix after number : %s \n\n",lineCount,yytext);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 97 "lexer.l"
{
    //Emply character constant error
    errorCount++;
    fprintf(logFile,"Error at line no %d: Empty character \n\n",lineCount);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 103 "lexer.l"
{
    //Unfinished character
    errorCount++;
    fprintf(logFile,"Error at line no %d: Unfinished character : %s \n\n",lineCount,yytext);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 110 "lexer.l"
{
    //character constant
    fprintf(logFile,"Line no %d: Token <CONST_CHAR> Lexeme %s found  --> <CONST_CHAR, %c> \n\n",lineCount,yytext,yytext[1]);
    fprintf(tokenFile,"<CONST_CHAR, %c> ",yytext[1]);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 116 "lexer.l"
{
    //Empty character
    errorCount++;
    fprintf(logFile,"Error at line no %d: Empty character constant \n\n",lineCount);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 122 "lexer.l"
{
    //character constant
    char ch;
    if(yytext[2]=='n')ch='\n';
    else if(yytext[2]=='t')ch='\t';
    else if(yytext[2]=='a')ch='\a';
    else if(yytext[2]=='f')ch='\f';
    else if(yytext[2]=='r')ch='\r';
    else if(yytext[2]=='b')ch='\b';
    else if(yytext[2]=='v')ch='\v';
    else if(yytext[2]=='0')ch='\0';
    else if(yytext[2]=='\\')ch='\\';
    else if(yytext[2]=='\'')ch='\'';
    fprintf(logFile,"Line no %d: Token <CONST_CHAR> Lexeme %s found --> <CONST_CHAR, %c>\n\n",lineCount,yytext,ch);
    fprintf(tokenFile,"<CONST_CHAR, %c> ",ch);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 139 "lexer.l"
{
    //Invalid character
    errorCount++;
    fprintf(logFile,"Error at line no %d: Invalid character : %s \n\n",lineCount,yytext);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 147 "lexer.l"
{
    fprintf(logFile,"Line no %d: Token <ADDOP> Lexeme %s found\n\n",lineCount,yytext);
    fprintf(tokenFile,"<ADDOP, %s> ",yytext);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 152 "lexer.l"
{
    fprintf(logFile,"Line no %d: Token <MULOP> Lexeme %s found\n\n",lineCount,yytext);
    fprintf(tokenFile,"<MULOP, %s> ",yytext);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 157 "lexer.l"
{
    fprintf(logFile,"Line no %d: Token <INCOP> Lexeme %s found\n\n",lineCount,yytext);
    fprintf(tokenFile,"<INCOP, %s> ",yytext);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 162 "lexer.l"
{
    fprintf(logFile,"Line no %d: Token <RELOP> Lexeme %s found\n\n",lineCount,yytext);
    fprintf(tokenFile,"<RELOP, %s> ",yytext);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 167 "lexer.l"
{
    fprintf(logFile,"Line no %d: Token <ASSIGNOP> Lexeme %s found\n\n",lineCount,yytext);
    fprintf(tokenFile,"<ASSIGNOP, %s> ",yytext);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 172 "lexer.l"
{
    fprintf(logFile,"Line no %d: Token <LOGICOP> Lexeme %s found\n\n",lineCount,yytext);
    fprintf(tokenFile,"<LOGICOP, %s> ",yytext);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 177 "lexer.l"
{
    fprintf(logFile,"Line no %d: Token <NOT> Lexeme %s found\n\n",lineCount,yytext);
    fprintf(tokenFile,"<NOT, %s> ",yytext);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 182 "lexer.l"
{
    fprintf(logFile,"Line no %d: Token <LPAREN> Lexeme %s found\n\n",lineCount,yytext);
    fprintf(tokenFile,"<LPAREN, %s> ",yytext);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 187 "lexer.l"
{
    fprintf(logFile,"Line no %d: Token <RPAREN> Lexeme %s found\n\n",lineCount,yytext);
    fprintf(tokenFile,"<RPAREN, %s> ",yytext);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 192 "lexer.l"
{
    fprintf(logFile,"Line no %d: Token <LCURL> Lexeme %s found\n\n",lineCount,yytext);
    fprintf(tokenFile,"<LCURL, %s> ",yytext);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 197 "lexer.l"
{
    fprintf(logFile,"Line no %d: Token <RCURL> Lexeme %s found\n\n",lineCount,yytext);
    fprintf(tokenFile,"<RCURL, %s> ",yytext);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 202 "lexer.l"
{
    fprintf(logFile,"Line no %d: Token <LTHIRD> Lexeme %s found\n\n",lineCount,yytext);
    fprintf(tokenFile,"<LTHIRD, %s> ",yytext);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 207 "lexer.l"
{
    fprintf(logFile,"Line no %d: Token <RTHIRD> Lexeme %s found\n\n",lineCount,yytext);
    fprintf(tokenFile,"<RTHIRD, %s> ",yytext);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 212 "lexer.l"
{
    fprintf(logFile,"Line no %d: Token <COMMA> Lexeme %s found\n\n",lineCount,yytext);
    fprintf(tokenFile,"<COMMA, %s> ",yytext);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 217 "lexer.l"
{
    fprintf(logFile,"Line no %d: Token <SEMICOLON> Lexeme %s found\n\n",lineCount,yytext);
    fprintf(tokenFile,"<SEMICOLON, %s> ",yytext);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 222 "lexer.l"
{
    commentBody="";
    tmpLineCount=lineCount;
	BEGIN COMMENT_SINGLE_LINE; 
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 228 "lexer.l"
{
    commentBody="";
    tmpLineCount=lineCount;
	BEGIN COMMENT_MULTI_LINE; 
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 234 "lexer.l"
{
    stringBody="";
    logStringBody="";
    tmpLineCount=lineCount;
	BEGIN STRING; 
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 241 "lexer.l"
{
    logStringBody+=yytext;
    lineCount++;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 246 "lexer.l"
{
    fprintf(logFile,"Line no %d: Token <STRING> Lexeme \"%s\" found --> <STRING, %s> \n\n",tmpLineCount,logStringBody.c_str(),stringBody.c_str());
    fprintf(tokenFile,"<STRING, %s> ",stringBody.c_str());
    BEGIN INITIAL; 
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 252 "lexer.l"
{
    errorCount++;
    fprintf(logFile,"Error at line no %d: Unterminated String \"%s \n\n",lineCount,stringBody.c_str());
    lineCount++;
    BEGIN INITIAL; 
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 261 "lexer.l"
{
    stringBody+=yytext;
    logStringBody+=yytext;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 266 "lexer.l"
{
    //character constant
    char ch;
    if(yytext[1]=='n')ch='\n';
    else if(yytext[1]=='t')ch='\t';
    else if(yytext[1]=='a')ch='\a';
    else if(yytext[1]=='f')ch='\f';
    else if(yytext[1]=='r')ch='\r';
    else if(yytext[1]=='b')ch='\b';
    else if(yytext[1]=='v')ch='\v';
    else if(yytext[1]=='0')ch='\0';
    else if(yytext[1]=='\\')ch='\\';
    else if(yytext[1]=='\'')ch='\'';
    stringBody+=ch;
    logStringBody+=yytext;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 283 "lexer.l"
{
    lineCount++;
    BEGIN INITIAL; 
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 288 "lexer.l"
{
    lineCount++;
    commentBody+=yytext;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 293 "lexer.l"
{
    commentBody+=yytext;
}
	YY_BREAK
case YY_STATE_EOF(COMMENT_MULTI_LINE):
#line 297 "lexer.l"
{
    errorCount++;
    fprintf(logFile,"Error at line no %d: Unterminated Comment \"%s \n\n",tmpLineCount,commentBody.c_str()); 
    return 0;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 303 "lexer.l"
{
    BEGIN INITIAL; 
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 307 "lexer.l"
{
    commentBody+=yytext;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 311 "lexer.l"
{lineCount++;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 313 "lexer.l"
{}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 315 "lexer.l"
{
    //Unrecognized character
    errorCount++;
    fprintf(logFile,"Error at line no %d: Unrecognized character : %s \n\n",lineCount,yytext);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 321 "lexer.l"
{lineCount++;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 322 "lexer.l"
ECHO;
	YY_BREAK
#line 1154 "lex.yy.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(COMMENT_SINGLE_LINE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */

yyFlexLexer::yyFlexLexer( istream* arg_yyin, ostream* arg_yyout )
	{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 1;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = 0;

	yy_current_buffer = 0;

#ifdef YY_USES_REJECT
	yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
	yy_state_buf = 0;
#endif
	}

yyFlexLexer::~yyFlexLexer()
	{
	delete yy_state_buf;
	yy_delete_buffer( yy_current_buffer );
	}

void yyFlexLexer::switch_streams( istream* new_in, ostream* new_out )
	{
	if ( new_in )
		{
		yy_delete_buffer( yy_current_buffer );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
		}

	if ( new_out )
		yyout = new_out;
	}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
	{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
	}

void yyFlexLexer::LexerOutput( const char* buf, int size )
	{
	(void) yyout->write( buf, size );
	}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

int yyFlexLexer::yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 146 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 146 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 145);

	return yy_is_jam ? 0 : yy_current_state;
	}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}


int yyFlexLexer::yyinput()
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


void yyFlexLexer::yyrestart( istream* input_file )
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


void yyFlexLexer::yy_load_buffer_state()
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( istream* file, int size )
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, istream* file )

	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	b->yy_is_interactive = 0;
	}


void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif


void yyFlexLexer::LexerError( yyconst char msg[] )
	{
	cerr << msg << '\n';
	exit( YY_EXIT_FAILURE );
	}


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 322 "lexer.l"

  

int main(int argc, char *argv[]){
    yyin = fopen(argv[1], "r");
    logFile=fopen(argv[2], "w");
    tokenFile=fopen(argv[3], "w");

    SymbolTable *symbolTable=new SymbolTable(7);

    yylex();
    fprintf(logFile,"Total lines: %d\nTotal errors: %d",lineCount,errorCount);
    fclose(yyin);
    fclose(logFile);
    fclose(tokenFile);
    return 0;
}